version: '3.8'

services:
  # ============================================
  # SANTE.GA NEURAL SERVER (Production)
  # ============================================
  neural-server:
    image: sante-ga-neural:latest
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sante-ga-neural-prod
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
      PORT: 3000
      
      # Supabase (Production)
      SUPABASE_URL: ${SUPABASE_URL}
      SUPABASE_ANON_KEY: ${SUPABASE_ANON_KEY}
      SUPABASE_SERVICE_ROLE_KEY: ${SUPABASE_SERVICE_ROLE_KEY}
      
      # Redis (Production)
      REDIS_ENABLED: "true"
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_PASSWORD: ${REDIS_PASSWORD}
      
      # JWT
      JWT_SECRET: ${JWT_SECRET}
      JWT_EXPIRES_IN: ${JWT_EXPIRES_IN:-24h}
      
      # Logging
      LOG_LEVEL: info
      
      # Frontend URL
      FRONTEND_URL: ${FRONTEND_URL}
    
    volumes:
      - ./logs:/app/logs
    
    depends_on:
      - redis
    
    networks:
      - sante-ga-network
    
    restart: always
    
    deploy:
      replicas: 2
      resources:
        limits:
          cpus: '1'
          memory: 1G
        reservations:
          cpus: '0.5'
          memory: 512M
      update_config:
        parallelism: 1
        delay: 10s

  # ============================================
  # REDIS (Production)
  # ============================================
  redis:
    image: redis:7-alpine
    container_name: sante-ga-redis-prod
    command: redis-server --requirepass ${REDIS_PASSWORD} --appendonly yes
    volumes:
      - redis-data:/data
    networks:
      - sante-ga-network
    restart: always
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 3s
      retries: 3

  # ============================================
  # NGINX (Reverse Proxy + SSL)
  # ============================================
  nginx:
    image: nginx:alpine
    container_name: sante-ga-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/ssl:/etc/nginx/ssl:ro
      - nginx-logs:/var/log/nginx
    depends_on:
      - neural-server
    networks:
      - sante-ga-network
    restart: always
    healthcheck:
      test: ["CMD", "nginx", "-t"]
      interval: 30s
      timeout: 3s
      retries: 3

volumes:
  redis-data:
  nginx-logs:

networks:
  sante-ga-network:
    driver: bridge
