import { createContext, useContext, useState, useEffect, ReactNode } from 'react';

type Language = 'fr' | 'en' | 'es' | 'ar' | 'pt';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

const translations: Record<Language, Record<string, string>> = {
  fr: {
    // Navigation
    'nav.home': 'Accueil',
    'nav.dashboard': 'Tableau de bord',
    'nav.appointments': 'Mes Rendez-vous',
    'nav.providers': 'Trouver un Prestataire',
    'nav.cartography': 'Cartographie Santé',
    'nav.prescriptions': 'Mes Ordonnances',
    'nav.results': 'Mes Résultats',
    'nav.medicalRecord': 'Mon Dossier Médical',
    'nav.reimbursements': 'Remboursements CNAMGS',
    'nav.support': 'Aide & Support',
    'nav.profile': 'Profil',
    'nav.insurance': 'Assurance',
    'nav.settings': 'Paramètres',
    'nav.logout': 'Déconnexion',
    'nav.about': 'À Propos',
    'nav.services': 'Nos Services',
    'nav.faq': 'FAQ',
    'nav.contact': 'Contact',
    'nav.adminDashboard': 'Tableau de Bord',
    'nav.project': 'Projet',
    'nav.users': 'Utilisateurs',
    'nav.approvals': 'Approbations',
    'nav.establishments': 'Établissements',
    'nav.professionals': 'Professionnels',
    'nav.demo': 'Démo',
    'nav.audit': 'Logs & Audit',
    
    // Dashboard & Appointments
    'dashboard.welcome': 'Bienvenue',
    'dashboard.quickActions': 'Actions rapides',
    'dashboard.myAppointments': 'Mes Rendez-vous',
    'dashboard.noAppointments': 'Aucun rendez-vous prévu',
    'dashboard.makeAppointment': 'Prendre rendez-vous',
    'dashboard.viewAllAppointments': 'Voir tous mes RDV',
    'dashboard.viewDetails': 'Voir détails',
    'dashboard.cancel': 'Annuler',
    'dashboard.consultation': 'Consultation',
    'dashboard.teleconsultation': 'Téléconsultation',
    'dashboard.exam': 'Examen',
    
    // Prescriptions
    'prescriptions.title': 'Mes Ordonnances',
    'prescriptions.new': 'Nouvelle',
    'prescriptions.news': 'Nouvelles',
    'prescriptions.notDispensed': 'Non dispensée',
    'prescriptions.dispensed': 'Dispensée',
    'prescriptions.expired': 'Expirée',
    'prescriptions.date': 'Date',
    'prescriptions.prescriber': 'Prescripteur',
    'prescriptions.medication': 'médicament',
    'prescriptions.medications': 'médicaments',
    'prescriptions.viewPrescription': 'Voir l\'ordonnance',
    'prescriptions.findPharmacy': 'Trouver une pharmacie',
    'prescriptions.viewAll': 'Toutes mes ordonnances',
    
    // Results
    'results.title': 'Mes Résultats d\'Examens',
    'results.new': 'Nouveau',
    'results.news': 'Nouveaux',
    'results.biology': 'Biologie',
    'results.imaging': 'Imagerie',
    'results.available': 'Disponible',
    'results.labCenter': 'Labo/Centre',
    'results.prescriber': 'Prescripteur',
    'results.downloadPdf': 'Télécharger PDF',
    'results.viewAll': 'Tous mes résultats',
    
    // Insurance
    'insurance.addInsurance': 'Ajoutez votre assurance',
    'insurance.addDescription': 'Pour suivre vos remboursements et simplifier vos démarches',
    'insurance.addButton': 'Ajouter mon assurance',
    'insurance.cnamgsInsured': 'Assuré CNAMGS',
    'insurance.cnssInsured': 'Assuré CNSS',
    'insurance.active': 'Actif',
    'insurance.checkRights': 'Vérifier mes droits',
    'insurance.coverageRate': 'Taux de couverture',
    'insurance.remainingBalance': 'Plafond restant',
    'insurance.contributionsUpToDate': 'Cotisations à jour',
    'insurance.toVerify': 'À vérifier',
    'insurance.lastContribution': 'Dernière cotisation',
    'insurance.consultCnss': 'Consulter e.CNSS.ga',
    
    // Quick Actions
    'quickActions.findDoctor': 'Trouver un médecin',
    'quickActions.pharmacies': 'Pharmacies de garde',
    'quickActions.teleconsultation': 'Téléconsultation urgente',
    'quickActions.hospitals': 'Hôpitaux proches',
    
    // Common
    'common.search': 'Rechercher',
    'common.notifications': 'Notifications',
    'common.loading': 'Chargement...',
    'common.error': 'Erreur',
    'common.success': 'Succès',
    'common.cancel': 'Annuler',
    'common.confirm': 'Confirmer',
    'common.save': 'Enregistrer',
    'common.delete': 'Supprimer',
    'common.edit': 'Modifier',
    'common.actions': 'Actions',
    'common.view': 'Voir',
    'common.export': 'Exporter',
    'common.filter': 'Filtrer',
    'common.reset': 'Réinitialiser',
    'common.noResults': 'Aucun résultat',
    'common.results': 'Résultats',
    
    // Admin
    'admin.dashboard': 'Administration SANTE.GA',
    'admin.subtitle': 'Gestion Complète de l\'Écosystème',
    'admin.users': 'Gestion des Utilisateurs',
    'admin.usersSubtitle': 'Administrez tous les utilisateurs de la plateforme SANTE.GA',
    'admin.totalUsers': 'Utilisateurs Total',
    'admin.activeUsers': 'Utilisateurs Actifs',
    'admin.pendingApprovals': 'En Attente',
    'admin.quickActions': 'Actions Rapides',
    'admin.recentActivity': 'Activité Récente',
    'admin.createUser': 'Créer un Utilisateur',
    'admin.createUserDesc': 'Ajouter un nouveau compte système',
    'admin.registerEstablishment': 'Enregistrer Établissement',
    'admin.registerEstablishmentDesc': 'Hôpital, clinique ou centre médical',
    'admin.exportData': 'Exporter Données',
    'admin.exportDataDesc': 'Rapports et statistiques système',
    'admin.allUsers': 'Tous les utilisateurs',
    'admin.manageRoles': 'Gérer les rôles',
    'admin.administrators': 'Administrateurs',
    'admin.patients': 'Patients',
    'admin.professionals': 'Professionnels',
    'admin.assignRole': 'Attribuer un rôle',
    'admin.accessDenied': 'Accès refusé',
    'admin.noPermission': 'Vous n\'avez pas les permissions nécessaires pour accéder à cette page.',
    
    // Approvals
    'approvals.title': 'Approbations en attente',
    'approvals.subtitle': 'Validez les inscriptions des professionnels de santé',
    'approvals.pending': 'en attente',
    'approvals.total': 'Total',
    'approvals.doctors': 'Médecins',
    'approvals.pharmacies': 'Pharmacies',
    'approvals.laboratories': 'Laboratoires',
    'approvals.hospitals': 'Hôpitaux',
    'approvals.allTypes': 'Tous les types',
    'approvals.examine': 'Examiner',
    'approvals.approve': 'Approuver',
    'approvals.reject': 'Refuser',
    'approvals.noPending': 'Aucune demande en attente',
    'approvals.allProcessed': 'Toutes les demandes ont été traitées',
    
    // Project Documentation
    'project.title': 'Documentation SANTE.GA',
    'project.subtitle': 'Plateforme nationale de santé numérique du Gabon',
    'project.version': 'v1.0.0',
    'project.productionReady': 'Production Ready',
    'project.overview': 'Vue d\'ensemble',
    'project.features': 'Fonctionnalités',
    'project.architecture': 'Architecture',
    'project.backend': 'Backend',
    'project.frontend': 'Frontend',
    'project.implementation': 'Implémentation',
    'project.security': 'Sécurité',
    'project.roadmap': 'Roadmap',
    'project.presentation': 'Présentation du Projet',
    'project.mission': 'Mission',
    'project.missionDesc': 'SANTE.GA est la plateforme nationale de santé numérique du Gabon qui vise à digitaliser et moderniser l\'écosystème de santé gabonais en connectant patients, professionnels de santé, établissements médicaux et organismes d\'assurance (CNAMGS, CNSS).',
    'project.mainObjectives': 'Objectifs Principaux',
    'project.healthcareAccess': 'Accessibilité des Soins',
    'project.healthcareAccessDesc': 'Faciliter l\'accès aux soins pour tous les Gabonais',
    'project.medicalRecord': 'Dossier Médical Unique',
    'project.medicalRecordDesc': 'Centraliser l\'historique médical de chaque patient',
    'project.adminManagement': 'Gestion Administrative',
    'project.adminManagementDesc': 'Simplifier les démarches et remboursements',
    'project.telemedicine': 'Télémédecine',
    'project.telemedicineDesc': 'Permettre les consultations à distance',
    'project.ecosystem': 'Écosystème',
    'project.systemActors': 'Acteurs du Système',
    'project.technologies': 'Technologies Utilisées',
    
    // Landing page
    'landing.secure': '100% Sécurisé et Gratuit',
    'landing.hero.title': 'La santé de tous,',
    'landing.hero.titleHighlight': 'partout, tout le temps',
    'landing.hero.subtitle': 'Plateforme e-santé du Gabon - Trouvez un médecin, prenez RDV, consultez vos résultats',
    'landing.hero.patient': 'Je suis Patient',
    'landing.hero.professional': 'Je suis Professionnel',
    'landing.howItWorks': 'Comment ça marche ?',
    'landing.howItWorksSubtitle': 'étapes simples pour gérer votre santé',
    'landing.step1.title': 'Trouvez votre prestataire',
    'landing.step1.desc': 'Recherchez parmi des milliers de médecins, cliniques et pharmacies à Libreville et partout au Gabon',
    'landing.step2.title': 'Prenez rendez-vous en ligne',
    'landing.step2.desc': 'Réservez votre consultation en quelques clics, 24h/24 et 7j/7',
    'landing.step3.title': 'Recevez vos ordonnances',
    'landing.step3.desc': 'Accédez à vos ordonnances, résultats et documents médicaux depuis votre téléphone',
    'landing.services': 'Services disponibles',
    'landing.servicesSubtitle': 'Tout ce dont vous avez besoin pour votre santé',
    'landing.service.medical': 'Consultation médicale',
    'landing.service.telehealth': 'Téléconsultation',
    'landing.service.pharmacy': 'Pharmacies 24/7',
    'landing.service.lab': 'Laboratoires',
    'landing.service.hospital': 'Hôpitaux & Cliniques',
    'landing.service.insurance': 'Suivi CNAMGS/CNSS',
    'landing.insurance.title': 'Votre assurance santé',
    'landing.insurance.subtitle': 'Vérifiez vos droits et suivez vos remboursements en temps réel',
    'landing.insurance.create': 'Créer mon compte gratuit',
    'landing.cta.title': 'Prêt à prendre en main votre santé ?',
    'landing.cta.subtitle': 'Rejoignez des milliers de Gabonais qui gèrent déjà leur santé en ligne',
    'landing.cta.patient': 'Créer mon compte patient',
    'landing.cta.login': 'Je me connecte',
    'landing.footer.tagline': 'Plateforme e-santé du Gabon pour un accès facilité aux soins',
    'landing.footer.about': 'À propos',
    'landing.footer.mission': 'Notre mission',
    'landing.footer.team': 'L\'équipe',
    'landing.footer.partners': 'Partenaires',
    'landing.footer.support': 'Support',
    'landing.footer.helpCenter': 'Centre d\'aide',
    'landing.footer.contact': 'Contact',
    'landing.footer.faq': 'FAQ',
    'landing.footer.legal': 'Légal',
    'landing.footer.terms': 'Mentions légales',
    'landing.footer.cgu': 'CGU',
    'landing.footer.privacy': 'Confidentialité',
    'landing.footer.copyright': 'SANTE.GA - Ministère de la Santé du Gabon',
    
    // Theme
    'theme.toggle': 'Basculer le thème',
    'theme.light': 'Clair',
    'theme.dark': 'Sombre',
    'theme.system': 'Système',
    
    // Language
    'language.toggle': 'Changer de langue',
    'language.fr': 'Français',
    'language.en': 'English',
    'language.es': 'Español',
    'language.ar': 'العربية',
    'language.pt': 'Português',
  },
  en: {
    // Navigation
    'nav.home': 'Home',
    'nav.dashboard': 'Dashboard',
    'nav.appointments': 'My Appointments',
    'nav.providers': 'Find a Provider',
    'nav.cartography': 'Health Map',
    'nav.prescriptions': 'My Prescriptions',
    'nav.results': 'My Results',
    'nav.medicalRecord': 'My Medical Record',
    'nav.reimbursements': 'CNAMGS Reimbursements',
    'nav.support': 'Help & Support',
    'nav.profile': 'Profile',
    'nav.insurance': 'Insurance',
    'nav.settings': 'Settings',
    'nav.logout': 'Logout',
    'nav.about': 'About',
    'nav.services': 'Our Services',
    'nav.faq': 'FAQ',
    'nav.contact': 'Contact',
    'nav.adminDashboard': 'Dashboard',
    'nav.project': 'Project',
    'nav.users': 'Users',
    'nav.approvals': 'Approvals',
    'nav.establishments': 'Establishments',
    'nav.professionals': 'Professionals',
    'nav.demo': 'Demo',
    'nav.audit': 'Logs & Audit',
    
    // Dashboard & Appointments
    'dashboard.welcome': 'Welcome',
    'dashboard.quickActions': 'Quick Actions',
    'dashboard.myAppointments': 'My Appointments',
    'dashboard.noAppointments': 'No scheduled appointments',
    'dashboard.makeAppointment': 'Make an appointment',
    'dashboard.viewAllAppointments': 'View all my appointments',
    'dashboard.viewDetails': 'View details',
    'dashboard.cancel': 'Cancel',
    'dashboard.consultation': 'Consultation',
    'dashboard.teleconsultation': 'Teleconsultation',
    'dashboard.exam': 'Exam',
    
    // Prescriptions
    'prescriptions.title': 'My Prescriptions',
    'prescriptions.new': 'New',
    'prescriptions.news': 'New',
    'prescriptions.notDispensed': 'Not dispensed',
    'prescriptions.dispensed': 'Dispensed',
    'prescriptions.expired': 'Expired',
    'prescriptions.date': 'Date',
    'prescriptions.prescriber': 'Prescriber',
    'prescriptions.medication': 'medication',
    'prescriptions.medications': 'medications',
    'prescriptions.viewPrescription': 'View prescription',
    'prescriptions.findPharmacy': 'Find a pharmacy',
    'prescriptions.viewAll': 'All my prescriptions',
    
    // Results
    'results.title': 'My Exam Results',
    'results.new': 'New',
    'results.news': 'New',
    'results.biology': 'Biology',
    'results.imaging': 'Imaging',
    'results.available': 'Available',
    'results.labCenter': 'Lab/Center',
    'results.prescriber': 'Prescriber',
    'results.downloadPdf': 'Download PDF',
    'results.viewAll': 'All my results',
    
    // Insurance
    'insurance.addInsurance': 'Add your insurance',
    'insurance.addDescription': 'To track reimbursements and simplify your procedures',
    'insurance.addButton': 'Add my insurance',
    'insurance.cnamgsInsured': 'CNAMGS Insured',
    'insurance.cnssInsured': 'CNSS Insured',
    'insurance.active': 'Active',
    'insurance.checkRights': 'Check my rights',
    'insurance.coverageRate': 'Coverage rate',
    'insurance.remainingBalance': 'Remaining balance',
    'insurance.contributionsUpToDate': 'Contributions up to date',
    'insurance.toVerify': 'To verify',
    'insurance.lastContribution': 'Last contribution',
    'insurance.consultCnss': 'Consult e.CNSS.ga',
    
    // Quick Actions
    'quickActions.findDoctor': 'Find a doctor',
    'quickActions.pharmacies': 'On-duty pharmacies',
    'quickActions.teleconsultation': 'Urgent teleconsultation',
    'quickActions.hospitals': 'Nearby hospitals',
    
    // Common
    'common.search': 'Search',
    'common.notifications': 'Notifications',
    'common.loading': 'Loading...',
    'common.error': 'Error',
    'common.success': 'Success',
    'common.cancel': 'Cancel',
    'common.confirm': 'Confirm',
    'common.save': 'Save',
    'common.delete': 'Delete',
    'common.edit': 'Edit',
    'common.actions': 'Actions',
    'common.view': 'View',
    'common.export': 'Export',
    'common.filter': 'Filter',
    'common.reset': 'Reset',
    'common.noResults': 'No results',
    'common.results': 'Results',
    
    // Admin
    'admin.dashboard': 'SANTE.GA Administration',
    'admin.subtitle': 'Complete Ecosystem Management',
    'admin.users': 'User Management',
    'admin.usersSubtitle': 'Manage all users of the SANTE.GA platform',
    'admin.totalUsers': 'Total Users',
    'admin.activeUsers': 'Active Users',
    'admin.pendingApprovals': 'Pending',
    'admin.quickActions': 'Quick Actions',
    'admin.recentActivity': 'Recent Activity',
    'admin.createUser': 'Create User',
    'admin.createUserDesc': 'Add a new system account',
    'admin.registerEstablishment': 'Register Establishment',
    'admin.registerEstablishmentDesc': 'Hospital, clinic or medical center',
    'admin.exportData': 'Export Data',
    'admin.exportDataDesc': 'System reports and statistics',
    'admin.allUsers': 'All users',
    'admin.manageRoles': 'Manage roles',
    'admin.administrators': 'Administrators',
    'admin.patients': 'Patients',
    'admin.professionals': 'Professionals',
    'admin.assignRole': 'Assign role',
    'admin.accessDenied': 'Access Denied',
    'admin.noPermission': 'You do not have the necessary permissions to access this page.',
    
    // Approvals
    'approvals.title': 'Pending Approvals',
    'approvals.subtitle': 'Validate healthcare professional registrations',
    'approvals.pending': 'pending',
    'approvals.total': 'Total',
    'approvals.doctors': 'Doctors',
    'approvals.pharmacies': 'Pharmacies',
    'approvals.laboratories': 'Laboratories',
    'approvals.hospitals': 'Hospitals',
    'approvals.allTypes': 'All types',
    'approvals.examine': 'Examine',
    'approvals.approve': 'Approve',
    'approvals.reject': 'Reject',
    'approvals.noPending': 'No pending requests',
    'approvals.allProcessed': 'All requests have been processed',
    
    // Project Documentation
    'project.title': 'SANTE.GA Documentation',
    'project.subtitle': 'Gabon\'s National Digital Health Platform',
    'project.version': 'v1.0.0',
    'project.productionReady': 'Production Ready',
    'project.overview': 'Overview',
    'project.features': 'Features',
    'project.architecture': 'Architecture',
    'project.backend': 'Backend',
    'project.frontend': 'Frontend',
    'project.implementation': 'Implementation',
    'project.security': 'Security',
    'project.roadmap': 'Roadmap',
    'project.presentation': 'Project Overview',
    'project.mission': 'Mission',
    'project.missionDesc': 'SANTE.GA is Gabon\'s national digital health platform that aims to digitize and modernize the Gabonese healthcare ecosystem by connecting patients, healthcare professionals, medical establishments and insurance organizations (CNAMGS, CNSS).',
    'project.mainObjectives': 'Main Objectives',
    'project.healthcareAccess': 'Healthcare Access',
    'project.healthcareAccessDesc': 'Facilitate access to healthcare for all Gabonese',
    'project.medicalRecord': 'Unified Medical Record',
    'project.medicalRecordDesc': 'Centralize each patient\'s medical history',
    'project.adminManagement': 'Administrative Management',
    'project.adminManagementDesc': 'Simplify procedures and reimbursements',
    'project.telemedicine': 'Telemedicine',
    'project.telemedicineDesc': 'Enable remote consultations',
    'project.ecosystem': 'Ecosystem',
    'project.systemActors': 'System Actors',
    'project.technologies': 'Technologies Used',
    
    // Landing page
    'landing.secure': '100% Secure and Free',
    'landing.hero.title': 'Healthcare for everyone,',
    'landing.hero.titleHighlight': 'everywhere, anytime',
    'landing.hero.subtitle': 'Gabon e-Health Platform - Find a doctor, book appointments, view your results',
    'landing.hero.patient': 'I am a Patient',
    'landing.hero.professional': 'I am a Professional',
    'landing.howItWorks': 'How it works?',
    'landing.howItWorksSubtitle': 'simple steps to manage your health',
    'landing.step1.title': 'Find your provider',
    'landing.step1.desc': 'Search among thousands of doctors, clinics and pharmacies in Libreville and throughout Gabon',
    'landing.step2.title': 'Book online',
    'landing.step2.desc': 'Book your consultation in a few clicks, 24/7',
    'landing.step3.title': 'Receive your prescriptions',
    'landing.step3.desc': 'Access your prescriptions, results and medical documents from your phone',
    'landing.services': 'Available Services',
    'landing.servicesSubtitle': 'Everything you need for your health',
    'landing.service.medical': 'Medical Consultation',
    'landing.service.telehealth': 'Telehealth',
    'landing.service.pharmacy': 'Pharmacies 24/7',
    'landing.service.lab': 'Laboratories',
    'landing.service.hospital': 'Hospitals & Clinics',
    'landing.service.insurance': 'CNAMGS/CNSS Tracking',
    'landing.insurance.title': 'Your health insurance',
    'landing.insurance.subtitle': 'Check your rights and track your reimbursements in real time',
    'landing.insurance.create': 'Create my free account',
    'landing.cta.title': 'Ready to take control of your health?',
    'landing.cta.subtitle': 'Join thousands of Gabonese already managing their health online',
    'landing.cta.patient': 'Create my patient account',
    'landing.cta.login': 'Sign in',
    'landing.footer.tagline': 'Gabon e-Health platform for easier access to care',
    'landing.footer.about': 'About',
    'landing.footer.mission': 'Our mission',
    'landing.footer.team': 'The team',
    'landing.footer.partners': 'Partners',
    'landing.footer.support': 'Support',
    'landing.footer.helpCenter': 'Help Center',
    'landing.footer.contact': 'Contact',
    'landing.footer.faq': 'FAQ',
    'landing.footer.legal': 'Legal',
    'landing.footer.terms': 'Legal Notice',
    'landing.footer.cgu': 'Terms of Use',
    'landing.footer.privacy': 'Privacy',
    'landing.footer.copyright': 'SANTE.GA - Ministry of Health of Gabon',
    
    // Theme
    'theme.toggle': 'Toggle theme',
    'theme.light': 'Light',
    'theme.dark': 'Dark',
    'theme.system': 'System',
    
    // Language
    'language.toggle': 'Change language',
    'language.fr': 'Français',
    'language.en': 'English',
    'language.es': 'Español',
    'language.ar': 'العربية',
    'language.pt': 'Português',
  },
  es: {
    // Navigation
    'nav.dashboard': 'Panel',
    'nav.appointments': 'Citas',
    'nav.providers': 'Profesionales',
    'nav.cartography': 'Cartografía',
    'nav.prescriptions': 'Recetas',
    'nav.results': 'Resultados',
    'nav.medicalRecord': 'Historial médico',
    'nav.reimbursements': 'Reembolsos',
    'nav.support': 'Soporte',
    'nav.profile': 'Perfil',
    'nav.insurance': 'Seguro',
    'nav.settings': 'Configuración',
    'nav.logout': 'Cerrar sesión',
    
    // Dashboard
    'dashboard.welcome': 'Bienvenido',
    'dashboard.quickActions': 'Acciones rápidas',
    'dashboard.upcomingAppointments': 'Próximas citas',
    'dashboard.activePrescriptions': 'Recetas activas',
    'dashboard.recentResults': 'Resultados recientes',
    'dashboard.insuranceStatus': 'Estado del seguro',
    
    // Quick Actions
    'quickActions.findDoctor': 'Encontrar un médico',
    'quickActions.pharmacies': 'Farmacias de guardia',
    'quickActions.teleconsultation': 'Teleconsulta urgente',
    'quickActions.hospitals': 'Hospitales cercanos',
    
    // Common
    'common.search': 'Buscar',
    'common.notifications': 'Notificaciones',
    'common.loading': 'Cargando...',
    'common.error': 'Error',
    'common.success': 'Éxito',
    'common.cancel': 'Cancelar',
    'common.confirm': 'Confirmar',
    'common.save': 'Guardar',
    'common.delete': 'Eliminar',
    'common.edit': 'Editar',
    
    // Theme
    'theme.toggle': 'Cambiar tema',
    'theme.light': 'Claro',
    'theme.dark': 'Oscuro',
    'theme.system': 'Sistema',
    
    // Landing page
    'landing.secure': '100% Seguro y Gratuito',
    'landing.hero.title': 'Salud para todos,',
    'landing.hero.titleHighlight': 'en todas partes, todo el tiempo',
    'landing.hero.subtitle': 'Plataforma e-Salud de Gabón - Encuentre un médico, reserve citas, consulte sus resultados',
    'landing.hero.patient': 'Soy Paciente',
    'landing.hero.professional': 'Soy Profesional',
    'landing.howItWorks': '¿Cómo funciona?',
    'landing.howItWorksSubtitle': 'pasos simples para gestionar su salud',
    'landing.step1.title': 'Encuentre su proveedor',
    'landing.step1.desc': 'Busque entre miles de médicos, clínicas y farmacias en Libreville y en todo Gabón',
    'landing.step2.title': 'Reserve en línea',
    'landing.step2.desc': 'Reserve su consulta en unos pocos clics, 24/7',
    'landing.step3.title': 'Reciba sus recetas',
    'landing.step3.desc': 'Acceda a sus recetas, resultados y documentos médicos desde su teléfono',
    'landing.services': 'Servicios disponibles',
    'landing.servicesSubtitle': 'Todo lo que necesita para su salud',
    'landing.service.medical': 'Consulta médica',
    'landing.service.telehealth': 'Telemedicina',
    'landing.service.pharmacy': 'Farmacias 24/7',
    'landing.service.lab': 'Laboratorios',
    'landing.service.hospital': 'Hospitales y Clínicas',
    'landing.service.insurance': 'Seguimiento CNAMGS/CNSS',
    'landing.insurance.title': 'Su seguro de salud',
    'landing.insurance.subtitle': 'Verifique sus derechos y siga sus reembolsos en tiempo real',
    'landing.insurance.create': 'Crear mi cuenta gratuita',
    'landing.cta.title': '¿Listo para tomar el control de su salud?',
    'landing.cta.subtitle': 'Únase a miles de gaboneses que ya gestionan su salud en línea',
    'landing.cta.patient': 'Crear mi cuenta de paciente',
    'landing.cta.login': 'Iniciar sesión',
    'landing.footer.tagline': 'Plataforma e-Salud de Gabón para un acceso más fácil a la atención',
    'landing.footer.about': 'Acerca de',
    'landing.footer.mission': 'Nuestra misión',
    'landing.footer.team': 'El equipo',
    'landing.footer.partners': 'Socios',
    'landing.footer.support': 'Soporte',
    'landing.footer.helpCenter': 'Centro de ayuda',
    'landing.footer.contact': 'Contacto',
    'landing.footer.faq': 'Preguntas frecuentes',
    'landing.footer.legal': 'Legal',
    'landing.footer.terms': 'Aviso legal',
    'landing.footer.cgu': 'Términos de uso',
    'landing.footer.privacy': 'Privacidad',
    'landing.footer.copyright': 'SANTE.GA - Ministerio de Salud de Gabón',
    
    // Language
    'language.toggle': 'Cambiar idioma',
    'language.fr': 'Français',
    'language.en': 'English',
    'language.es': 'Español',
    'language.ar': 'العربية',
    'language.pt': 'Português',
  },
  ar: {
    // Navigation
    'nav.dashboard': 'لوحة التحكم',
    'nav.appointments': 'المواعيد',
    'nav.providers': 'المهنيون',
    'nav.cartography': 'الخرائط',
    'nav.prescriptions': 'الوصفات',
    'nav.results': 'النتائج',
    'nav.medicalRecord': 'السجل الطبي',
    'nav.reimbursements': 'التعويضات',
    'nav.support': 'الدعم',
    'nav.profile': 'الملف الشخصي',
    'nav.insurance': 'التأمين',
    'nav.settings': 'الإعدادات',
    'nav.logout': 'تسجيل الخروج',
    
    // Dashboard
    'dashboard.welcome': 'مرحبا',
    'dashboard.quickActions': 'إجراءات سريعة',
    'dashboard.upcomingAppointments': 'المواعيد القادمة',
    'dashboard.activePrescriptions': 'الوصفات النشطة',
    'dashboard.recentResults': 'النتائج الأخيرة',
    'dashboard.insuranceStatus': 'حالة التأمين',
    
    // Quick Actions
    'quickActions.findDoctor': 'ابحث عن طبيب',
    'quickActions.pharmacies': 'الصيدليات المناوبة',
    'quickActions.teleconsultation': 'استشارة عن بعد عاجلة',
    'quickActions.hospitals': 'المستشفيات القريبة',
    
    // Common
    'common.search': 'بحث',
    'common.notifications': 'الإشعارات',
    'common.loading': 'جاري التحميل...',
    'common.error': 'خطأ',
    'common.success': 'نجح',
    'common.cancel': 'إلغاء',
    'common.confirm': 'تأكيد',
    'common.save': 'حفظ',
    'common.delete': 'حذف',
    'common.edit': 'تعديل',
    
    // Theme
    'theme.toggle': 'تبديل المظهر',
    'theme.light': 'فاتح',
    'theme.dark': 'داكن',
    'theme.system': 'النظام',
    
    // Landing page
    'landing.secure': 'آمن ومجاني 100%',
    'landing.hero.title': 'الصحة للجميع،',
    'landing.hero.titleHighlight': 'في كل مكان، في كل وقت',
    'landing.hero.subtitle': 'منصة الصحة الإلكترونية في الغابون - ابحث عن طبيب، احجز مواعيد، اطلع على نتائجك',
    'landing.hero.patient': 'أنا مريض',
    'landing.hero.professional': 'أنا محترف',
    'landing.howItWorks': 'كيف يعمل؟',
    'landing.howItWorksSubtitle': 'خطوات بسيطة لإدارة صحتك',
    'landing.step1.title': 'ابحث عن مزود الخدمة',
    'landing.step1.desc': 'ابحث بين آلاف الأطباء والعيادات والصيدليات في ليبرفيل وفي جميع أنحاء الغابون',
    'landing.step2.title': 'احجز عبر الإنترنت',
    'landing.step2.desc': 'احجز استشارتك بنقرات قليلة، 24/7',
    'landing.step3.title': 'استلم وصفاتك الطبية',
    'landing.step3.desc': 'الوصول إلى وصفاتك الطبية ونتائجك ومستنداتك الطبية من هاتفك',
    'landing.services': 'الخدمات المتاحة',
    'landing.servicesSubtitle': 'كل ما تحتاجه لصحتك',
    'landing.service.medical': 'استشارة طبية',
    'landing.service.telehealth': 'الطب عن بعد',
    'landing.service.pharmacy': 'صيدليات 24/7',
    'landing.service.lab': 'مختبرات',
    'landing.service.hospital': 'مستشفيات وعيادات',
    'landing.service.insurance': 'متابعة CNAMGS/CNSS',
    'landing.insurance.title': 'تأمينك الصحي',
    'landing.insurance.subtitle': 'تحقق من حقوقك وتتبع مبالغ التعويض في الوقت الفعلي',
    'landing.insurance.create': 'إنشاء حسابي المجاني',
    'landing.cta.title': 'هل أنت مستعد للسيطرة على صحتك؟',
    'landing.cta.subtitle': 'انضم إلى آلاف الغابونيين الذين يديرون صحتهم بالفعل عبر الإنترنت',
    'landing.cta.patient': 'إنشاء حساب المريض الخاص بي',
    'landing.cta.login': 'تسجيل الدخول',
    'landing.footer.tagline': 'منصة الصحة الإلكترونية في الغابون لسهولة الوصول إلى الرعاية',
    'landing.footer.about': 'حول',
    'landing.footer.mission': 'مهمتنا',
    'landing.footer.team': 'الفريق',
    'landing.footer.partners': 'الشركاء',
    'landing.footer.support': 'الدعم',
    'landing.footer.helpCenter': 'مركز المساعدة',
    'landing.footer.contact': 'اتصل',
    'landing.footer.faq': 'الأسئلة الشائعة',
    'landing.footer.legal': 'قانوني',
    'landing.footer.terms': 'إشعار قانوني',
    'landing.footer.cgu': 'شروط الاستخدام',
    'landing.footer.privacy': 'الخصوصية',
    'landing.footer.copyright': 'SANTE.GA - وزارة الصحة في الغابون',
    
    // Language
    'language.toggle': 'تغيير اللغة',
    'language.fr': 'Français',
    'language.en': 'English',
    'language.es': 'Español',
    'language.ar': 'العربية',
    'language.pt': 'Português',
  },
  pt: {
    // Navigation
    'nav.dashboard': 'Painel',
    'nav.appointments': 'Consultas',
    'nav.providers': 'Profissionais',
    'nav.cartography': 'Cartografia',
    'nav.prescriptions': 'Receitas',
    'nav.results': 'Resultados',
    'nav.medicalRecord': 'Prontuário médico',
    'nav.reimbursements': 'Reembolsos',
    'nav.support': 'Suporte',
    'nav.profile': 'Perfil',
    'nav.insurance': 'Seguro',
    'nav.settings': 'Configurações',
    'nav.logout': 'Sair',
    
    // Dashboard
    'dashboard.welcome': 'Bem-vindo',
    'dashboard.quickActions': 'Ações rápidas',
    'dashboard.upcomingAppointments': 'Próximas consultas',
    'dashboard.activePrescriptions': 'Receitas ativas',
    'dashboard.recentResults': 'Resultados recentes',
    'dashboard.insuranceStatus': 'Status do seguro',
    
    // Quick Actions
    'quickActions.findDoctor': 'Encontrar um médico',
    'quickActions.pharmacies': 'Farmácias de plantão',
    'quickActions.teleconsultation': 'Teleconsulta urgente',
    'quickActions.hospitals': 'Hospitais próximos',
    
    // Common
    'common.search': 'Pesquisar',
    'common.notifications': 'Notificações',
    'common.loading': 'Carregando...',
    'common.error': 'Erro',
    'common.success': 'Sucesso',
    'common.cancel': 'Cancelar',
    'common.confirm': 'Confirmar',
    'common.save': 'Salvar',
    'common.delete': 'Excluir',
    'common.edit': 'Editar',
    
    // Theme
    'theme.toggle': 'Alternar tema',
    'theme.light': 'Claro',
    'theme.dark': 'Escuro',
    'theme.system': 'Sistema',
    
    // Landing page
    'landing.secure': '100% Seguro e Gratuito',
    'landing.hero.title': 'Saúde para todos,',
    'landing.hero.titleHighlight': 'em todos os lugares, o tempo todo',
    'landing.hero.subtitle': 'Plataforma e-Saúde do Gabão - Encontre um médico, marque consultas, veja seus resultados',
    'landing.hero.patient': 'Sou Paciente',
    'landing.hero.professional': 'Sou Profissional',
    'landing.howItWorks': 'Como funciona?',
    'landing.howItWorksSubtitle': 'passos simples para gerenciar sua saúde',
    'landing.step1.title': 'Encontre seu prestador',
    'landing.step1.desc': 'Pesquise entre milhares de médicos, clínicas e farmácias em Libreville e em todo o Gabão',
    'landing.step2.title': 'Reserve online',
    'landing.step2.desc': 'Marque sua consulta em poucos cliques, 24/7',
    'landing.step3.title': 'Receba suas receitas',
    'landing.step3.desc': 'Acesse suas receitas, resultados e documentos médicos do seu telefone',
    'landing.services': 'Serviços disponíveis',
    'landing.servicesSubtitle': 'Tudo o que você precisa para sua saúde',
    'landing.service.medical': 'Consulta médica',
    'landing.service.telehealth': 'Telemedicina',
    'landing.service.pharmacy': 'Farmácias 24/7',
    'landing.service.lab': 'Laboratórios',
    'landing.service.hospital': 'Hospitais e Clínicas',
    'landing.service.insurance': 'Rastreamento CNAMGS/CNSS',
    'landing.insurance.title': 'Seu seguro de saúde',
    'landing.insurance.subtitle': 'Verifique seus direitos e acompanhe seus reembolsos em tempo real',
    'landing.insurance.create': 'Criar minha conta gratuita',
    'landing.cta.title': 'Pronto para assumir o controle de sua saúde?',
    'landing.cta.subtitle': 'Junte-se a milhares de gaboneses que já gerenciam sua saúde online',
    'landing.cta.patient': 'Criar minha conta de paciente',
    'landing.cta.login': 'Entrar',
    'landing.footer.tagline': 'Plataforma e-Saúde do Gabão para facilitar o acesso aos cuidados',
    'landing.footer.about': 'Sobre',
    'landing.footer.mission': 'Nossa missão',
    'landing.footer.team': 'A equipe',
    'landing.footer.partners': 'Parceiros',
    'landing.footer.support': 'Suporte',
    'landing.footer.helpCenter': 'Centro de ajuda',
    'landing.footer.contact': 'Contato',
    'landing.footer.faq': 'Perguntas frequentes',
    'landing.footer.legal': 'Legal',
    'landing.footer.terms': 'Aviso legal',
    'landing.footer.cgu': 'Termos de uso',
    'landing.footer.privacy': 'Privacidade',
    'landing.footer.copyright': 'SANTE.GA - Ministério da Saúde do Gabão',
    
    // Language
    'language.toggle': 'Mudar idioma',
    'language.fr': 'Français',
    'language.en': 'English',
    'language.es': 'Español',
    'language.ar': 'العربية',
    'language.pt': 'Português',
  },
};

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguageState] = useState<Language>(() => {
    const stored = localStorage.getItem('language');
    return (stored as Language) || 'fr';
  });

  useEffect(() => {
    localStorage.setItem('language', language);
    document.documentElement.lang = language;
    document.documentElement.dir = language === 'ar' ? 'rtl' : 'ltr';
  }, [language]);

  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within LanguageProvider');
  }
  return context;
}
