export const EventTypes = {
  USER_REGISTERED: 'USER_REGISTERED',
  USER_LOGIN: 'USER_LOGIN',
  USER_LOGOUT: 'USER_LOGOUT',
  PASSWORD_RESET_REQUESTED: 'PASSWORD_RESET_REQUESTED',
  
  PATIENT_REGISTERED: 'PATIENT_REGISTERED',
  PATIENT_PROFILE_UPDATED: 'PATIENT_PROFILE_UPDATED',
  PATIENT_INSURANCE_VERIFIED: 'PATIENT_INSURANCE_VERIFIED',
  PATIENT_DELETED: 'PATIENT_DELETED',
  
  PROFESSIONAL_REGISTERED: 'PROFESSIONAL_REGISTERED',
  PROFESSIONAL_VERIFIED: 'PROFESSIONAL_VERIFIED',
  PROFESSIONAL_PROFILE_UPDATED: 'PROFESSIONAL_PROFILE_UPDATED',
  
  APPOINTMENT_CREATED: 'APPOINTMENT_CREATED',
  APPOINTMENT_CONFIRMED: 'APPOINTMENT_CONFIRMED',
  APPOINTMENT_CANCELLED: 'APPOINTMENT_CANCELLED',
  APPOINTMENT_COMPLETED: 'APPOINTMENT_COMPLETED',
  APPOINTMENT_REMINDER_SENT: 'APPOINTMENT_REMINDER_SENT',
  
  PRESCRIPTION_CREATED: 'PRESCRIPTION_CREATED',
  PRESCRIPTION_SENT_TO_PHARMACY: 'PRESCRIPTION_SENT_TO_PHARMACY',
  PRESCRIPTION_DISPENSED: 'PRESCRIPTION_DISPENSED',
  
  NOTIFICATION_SENT: 'NOTIFICATION_SENT',
  SMS_SENT: 'SMS_SENT',
  EMAIL_SENT: 'EMAIL_SENT',
  PUSH_NOTIFICATION_SENT: 'PUSH_NOTIFICATION_SENT',
  
  SYSTEM_ERROR: 'SYSTEM_ERROR',
  HEALTH_CHECK_REQUESTED: 'HEALTH_CHECK_REQUESTED'
};

export default EventTypes;
